# Voice Hub Docker Compose
#
# Quickstart (Oracle Cloud VM)
# 1. Run `git submodule update --init --recursive` to fetch MCP services.
# 2. Copy `.env.example` to `.env` and adjust values if needed.
# 3. Start all services with `docker compose up --build`.
#
# Services listen on the ports defined below. Ensure these ports are
# accessible in your Oracle Cloud firewall settings.
version: '3.8'
services:
  openhands:
    build:
      context: ./external/OpenHands/containers/app
    container_name: openhands
    ports:
      - "${PORT_OPENHANDS}:3000"
    restart: unless-stopped

  gmail-mcp:
    build:
      context: ./external/Gmail-MCP-Server
    container_name: gmail-mcp
    ports:
      - "${PORT_GMAIL_MCP}:3000"
    restart: unless-stopped

  glue:
    build:
      context: ./src/glue
    container_name: glue
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - OPENHANDS_API=${OPENHANDS_API}
    depends_on:
      - openhands
    ports:
      - "${PORT_GLUE}:8080"
    restart: unless-stopped
