version: '3.9'
services:
  glue-webhook:
    build: ./glue-webhook
    container_name: glue-webhook
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - caddy-shared

networks:
  caddy-shared:
    external: true
